import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Login.module.scss";
import githubImg from "../assets/github-logo.png";
import googleImg from "../assets/google-logo.png";
import { useAuth } from "../contexts/AuthContext";

const Login: NextPage = () => {
  const { googleSignIn } = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button id="google" onClick={() => googleSignIn()}>
          <Image
            className="icon"
            src={googleImg}
            alt=""
            height={20}
            width={20}
          />
          <p className="button-text">Continue with google</p>
        </button>
      </main>
    </div>
  );
};

export default Login;
